package xyz.savvamirzoyan.wordremember.ui.state

enum class VerbFormType {
    PRASENS_ICH, PRASENS_DU, PRASENS_ER_SIE_ES, PRASENS_WIR, PRASENS_IHR, PRASENS_SIE_SIE,

    PRATERITUM_ICH, PRATERITUM_DU, PRATERITUM_ER_SIE_ES, PRATERITUM_WIR, PRATERITUM_IHR, PRATERITUM_SIE_SIE,

    PERFEKT
}